### ISSUE TITLE
Provider crashes on SSH key label change

### ISSUE THREAD

**Issue by peterpramb** [hetznercloud/terraform-provider-hcloud#147]
Though not explicitly listed as [argument](https://www.terraform.io/docs/providers/hcloud/r/ssh_key.html) (probably intentional), I tried to play around with `labels` on `hcloud_ssh_key` resources.

Interestingly the `labels` argument is accepted happily without any issues, and also *creating* a SSH key with labels on it works flawlessly.

Unfortunately when trying to *modify* or *remove* existing labels on a SSH key, the `hcloud` provider crashes badly:
```
hcloud_ssh_key.default: Modifying... [id=1241954]

Error: rpc error: code = Unavailable desc = transport is closing
```
From the `crash.log`:
```
2020/02/01 16:53:07 [DEBUG] Starting graph walk: walkApply
2020-02-01T16:53:07.286+0100 [DEBUG] plugin: starting plugin: path=/home/terraform/hcloud/infra/.terraform/plugins/linux_amd64/terraform-provider-hcloud_v1.15.0_x4 args=[/home/terraform/hcloud/infra/.terraform/plugins/linux_amd64/terraform-provider-hcloud_v1.15.0_x4]
2020-02-01T16:53:07.288+0100 [DEBUG] plugin: plugin started: path=/home/terraform/hcloud/infra/.terraform/plugins/linux_amd64/terraform-provider-hcloud_v1.15.0_x4 pid=28233
2020-02-01T16:53:07.288+0100 [DEBUG] plugin: waiting for RPC address: path=/home/terraform/hcloud/infra/.terraform/plugins/linux_amd64/terraform-provider-hcloud_v1.15.0_x4
2020-02-01T16:53:07.529+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: plugin address: address=/tmp/plugin881323313 network=unix timestamp=2020-02-01T16:53:07.528+0100
2020-02-01T16:53:07.529+0100 [DEBUG] plugin: using plugin: version=5
2020/02/01 16:53:07 [DEBUG] hcloud_ssh_key.default: applying the planned Update change
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: panic: interface conversion: interface {} is map[string]interface {}, not map[string]string
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: 
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: goroutine 28 [running]:
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: github.com/terraform-providers/terraform-provider-hcloud/hcloud.resourceSSHKeyUpdate(0xc00026eb60, 0xfb46e0, 0xc00011cb60, 0x24, 0x1aa9b80)
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-hcloud/hcloud/resource_hcloud_sshkey.go:136 +0xb63
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000100b80, 0xc000018e10, 0xc000141b00, 0xfb46e0, 0xc00011cb60, 0xc000478c01, 0xc000258a50, 0x40eac3)
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.3.0/helper/schema/resource.go:311 +0x263
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000101580, 0xc00026b918, 0xc000018e10, 0xc000141b00, 0xc00025a988, 0xc0001300b8, 0xf2a900)
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.3.0/helper/schema/provider.go:294 +0x99
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000aea10, 0x13439e0, 0xc0001b9aa0, 0xc000128900, 0xc0000aea10, 0xc0001b9aa0, 0xc0000a4a80)
2020-02-01T16:53:07.994+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.3.0/internal/helper/plugin/grpc_provider.go:885 +0x882
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x106d5a0, 0xc0000aea10, 0x13439e0, 0xc0001b9aa0, 0xc0001288a0, 0x0, 0x13439e0, 0xc0001b9aa0, 0xc000252700, 0x6b7)
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.3.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ce000, 0x134fb80, 0xc00028cc00, 0xc0001c2200, 0xc000110240, 0x1a7da60, 0x0, 0x0, 0x0)
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x460
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc0000ce000, 0x134fb80, 0xc00028cc00, 0xc0001c2200, 0x0)
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xd97
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000ac380, 0xc0000ce000, 0x134fb80, 0xc00028cc00, 0xc0001c2200)
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xbb
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-02-01T16:53:07.995+0100 [DEBUG] plugin.terraform-provider-hcloud_v1.15.0_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
2020-02-01T16:53:07.998+0100 [DEBUG] plugin: plugin process exited: path=/home/terraform/hcloud/infra/.terraform/plugins/linux_amd64/terraform-provider-hcloud_v1.15.0_x4 pid=28233 error="exit status 2"
2020/02/01 16:53:07 [DEBUG] hcloud_ssh_key.default: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020-02-01T16:53:08.111+0100 [DEBUG] plugin: plugin exited
```
In the trace log I find the two retrieval requests:
```
GET /v1/ssh_keys/1241954 HTTP/1.1
Host: api.hetzner.cloud
Authorization: Bearer ...
User-Agent: hcloud-terraform/1.13.0 hcloud-go/1.17.0
```
```
GET /v1/ssh_keys?page=1 HTTP/1.1
Host: api.hetzner.cloud
Authorization: Bearer ...
User-Agent: hcloud-terraform/1.13.0 hcloud-go/1.17.0
```
But no modification request afterwards, so either the provider crashes already before the request or has no chance to provide the debug output anymore. From the panic above it's probably the former case:
```
panic: interface conversion: interface {} is map[string]interface {}, not map[string]string
```

**Steps to reproduce**:
1. Create a new managed SSH key:
```
provider "hcloud" {
  token = "sometoken"
}

resource "hcloud_ssh_key" "default" {
  name       = "testing"
  public_key = file("test.pub")
  labels     = {
    environment" = "DEV"
    managed" = "true"
    managed_by" = "Terraform"
  }
}
```
```
data.hcloud_ssh_keys.default: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # hcloud_ssh_key.default will be created
  + resource "hcloud_ssh_key" "default" {
      + fingerprint = (known after apply)
      + id          = (known after apply)
      + labels      = {
          + "environment" = "DEV"
          + "managed"     = "true"
          + "managed_by"  = "Terraform"
        }
      + name        = "testing"
      + public_key  = <<~EOT
            ... 
        EOT
    }

Plan: 1 to add, 0 to change, 0 to destroy.

hcloud_ssh_key.default: Creating...
hcloud_ssh_key.default: Creation complete after 1s [id=1241979]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
2. Verify the SSH key:
```
provider "hcloud" {
  token = "sometoken"
}

data "hcloud_ssh_keys" "default" {
}

output "hcloud_ssh_keys" {
  value = data.hcloud_ssh_keys.default.ssh_keys
}
```
```
data.hcloud_ssh_keys.default: Refreshing state...
hcloud_ssh_key.default: Refreshing state... [id=1241979]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

hcloud_ssh_keys = [
  {
    "fingerprint" = "46:15:79:c8:1a:63:5f:a6:de:9a:4d:f7:6d:40:90:cb"
    "id" = 1241979
    "labels" = {
      "environment" = "DEV"
      "managed" = "true"
      "managed_by" = "Terraform"
    }
    "name" = "testing"
    "public_key" = "...\n"
  },
]
```
3. Modify (or remove) an existing label:
```
provider "hcloud" {
  token = "sometoken"
}

resource "hcloud_ssh_key" "default" {
  name       = "testing"
  public_key = file("test.pub")
  labels     = {
    environment" = "FAT"
    managed" = "true"
    managed_by" = "Terraform"
  }
}
```
```
hcloud_ssh_key.default: Refreshing state... [id=1241979]
data.hcloud_ssh_keys.default: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # hcloud_ssh_key.default will be updated in-place
  ~ resource "hcloud_ssh_key" "default" {
        fingerprint = "46:15:79:c8:1a:63:5f:a6:de:9a:4d:f7:6d:40:90:cb"
        id          = "1241979"
      ~ labels      = {
          ~ "environment" = "DEV" -> "FAT"
            "managed"     = "true"
            "managed_by"  = "Terraform"
        }
        name        = "testing"
        public_key  = <<~EOT
            ...
        EOT
    }

Plan: 0 to add, 1 to change, 0 to destroy.

hcloud_ssh_key.default: Modifying... [id=1241979]

Error: rpc error: code = Unavailable desc = transport is closing
```

**Comment by peterpramb** [comment]
Sorry, I forgot:
```
Terraform v0.12.20
+ provider.hcloud v1.15.0
```
So even though `labels` are not officially supported: Is someone interested in following up with this?
