### ISSUE TITLE
Plugin did not respond

### ISSUE THREAD

**Issue by eBeyond** [hetznercloud/terraform-provider-hcloud#375]
hcloud failed to destroy in terraform cloud:

This happens with Terraform 0.15.5 and 1.0.0
Using latest hcloud (1.26.1)

`[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
[31m│[0m [0mcontain more details.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
[31m│[0m [0mcontain more details.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
[31m│[0m [0mcontain more details.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
[31m│[0m [0mcontain more details.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
[31m│[0m [0mcontain more details.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
[31m│[0m [0mcontain more details.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
[31m│[0m [0mcontain more details.
[31m╵[0m[0m

Stack trace from the terraform-provider-hcloud_v1.26.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaf80f6]

goroutine 135 [running]:
github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress.func1(0xc00066a6c0, 0xc000638e40, 0xc00020a420, 0x1, 0x1, 0xc000218c78, 0x10fd778, 0xc0001d79e0)
	github.com/hetznercloud/hcloud-go@v1.25.0/hcloud/action.go:196 +0x176
created by github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress
	github.com/hetznercloud/hcloud-go@v1.25.0/hcloud/action.go:189 +0xde

Error: The terraform-provider-hcloud_v1.26.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

**Comment by eBeyond** [comment]
Closing it...
It's one of the horrible error messages terraform provides...

**Comment by eBeyond** [comment]
Close
