### ISSUE TITLE
[Bug]: Crash when destroying infrastructure

### ISSUE THREAD

**Issue by pitastrudl** [hetznercloud/terraform-provider-hcloud#516]
### What happened?

I had defined a simple infrastructure via hetzner. Seems to have started happening when i started to use https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/floating_ip and the assignment resource. I was fiddling with `  delete_protection = false ` as well, trying it out. But now even after removing the floating ip resources, the error seems to persist. I did `terraform refresh` and the destroy action worked afterwards (also removed the floating ip resources from code). It also works if I try to destroy another time after the first failed attempt. 

Using terraform on Arch Linux. The error occured when doing `terraform destroy` 

logs:

```
hcloud_server_network.web_network2[1]: Destroying... [id=19397790-1533801]
hcloud_volume_attachment.web_vol_attachment[0]: Destroying... [id=18451737]
hcloud_volume_attachment.web_vol_attachment[1]: Destroying... [id=18451733]
hcloud_floating_ip_assignment.main: Destroying... [id=5098091]
hcloud_server_network.web_network[1]: Destroying... [id=19397790-1533801]
hcloud_volume_attachment.web_vol_attachment[2]: Destroying... [id=18451735]
hcloud_server_network.web_network2[0]: Destroying... [id=19397791-1533801]
hcloud_server_network.web_network[0]: Destroying... [id=19397791-1533801]
hcloud_network_subnet.hc_private_subnet2: Destroying... [id=1533801-xxxx/24]
hcloud_server_network.web_network2[2]: Destroying... [id=19397792-1533801]
hcloud_volume_attachment.web_vol_attachment[2]: Still destroying... [id=18451735, 10s elapsed]
hcloud_server_network.web_network2[1]: Still destroying... [id=19397790-1533801, 10s elapsed]
hcloud_network_subnet.hc_private_subnet2: Still destroying... [id=1533801 xxxxx/24, 10s elapsed]
hcloud_server_network.web_network2[0]: Still destroying... [id=19397791-1533801, 10s elapsed]
hcloud_volume_attachment.web_vol_attachment[1]: Still destroying... [id=18451733, 10s elapsed]
hcloud_server_network.web_network[0]: Still destroying... [id=19397791-1533801, 10s elapsed]
hcloud_volume_attachment.web_vol_attachment[0]: Still destroying... [id=18451737, 10s elapsed]
hcloud_floating_ip_assignment.main: Still destroying... [id=5098091, 10s elapsed]
hcloud_server_network.web_network[1]: Still destroying... [id=19397790-1533801, 10s elapsed]
hcloud_server_network.web_network2[2]: Still destroying... [id=19397792-1533801, 10s elapsed]
hcloud_floating_ip_assignment.main: Destruction complete after 11s
hcloud_server_network.web_network[2]: Destroying... [id=19397792-1533801]
hcloud_network_subnet.hc_private_subnet2: Destruction complete after 12s
hcloud_floating_ip.master: Destroying... [id=5098091]
hcloud_floating_ip.master: Destruction complete after 0s
hcloud_volume_attachment.web_vol_attachment[2]: Destruction complete after 13s
hcloud_volume_attachment.web_vol_attachment[0]: Destruction complete after 13s
hcloud_volume_attachment.web_vol_attachment[1]: Destruction complete after 13s
hcloud_volume.web_server_volume[1]: Destroying... [id=18451733]
hcloud_volume.web_server_volume[2]: Destroying... [id=18451735]
hcloud_volume.web_server_volume[0]: Destroying... [id=18451737]
hcloud_volume.web_server_volume[1]: Destruction complete after 1s
hcloud_volume.web_server_volume[2]: Destruction complete after 1s
hcloud_server_network.web_network[0]: Destruction complete after 14s
hcloud_volume.web_server_volume[0]: Destruction complete after 2s
hcloud_server_network.web_network[1]: Destruction complete after 18s
hcloud_server_network.web_network[2]: Destruction complete after 7s
hcloud_server_network.web_network2[1]: Still destroying... [id=19397790-1533801, 20s elapsed]
hcloud_server_network.web_network2[0]: Still destroying... [id=19397791-1533801, 20s elapsed]
hcloud_server_network.web_network2[2]: Still destroying... [id=19397792-1533801, 20s elapsed]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-hcloud_v1.33.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6b96f]

goroutine 283 [running]:
github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress.func1()
        github.com/hetznercloud/hcloud-go@v1.33.1/hcloud/action.go:196 +0x1af
created by github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress
        github.com/hetznercloud/hcloud-go@v1.33.1/hcloud/action.go:189 +0x133

Error: The terraform-provider-hcloud_v1.33.0 plugin crashed!
```

### What did you expect to happen?

The infrastructure to destroy.

### Please provide a minimal working example

.

**Comment by pitastrudl** [comment]
Updated to `v1.33.1`, experiencing the same issue.

**Comment by pitastrudl** [comment]
Updated terraform to v1.1.8. and I have no more issues destroying/applying, seemed it was fixed: https://github.com/hashicorp/terraform/releases/tag/v1.1.8
