### ISSUE TITLE
[Bug]: Plugin crash while destroying infrastructure

### ISSUE THREAD

**Issue by pitastrudl** [hetznercloud/terraform-provider-hcloud#530]
Using terraform v1.1.9 and v1.33.2 hcloud provider

### What happened?

simple `terraform destroy` action. 

```
hcloud_server_network.main_network[1]: Destruction complete after 9s
hcloud_server_network.main_network[2]: Still destroying... [id=20587124-1661743, 10s elapsed]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-hcloud_v1.33.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa9ee37]

goroutine 285 [running]:
github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress.func1()
        github.com/hetznercloud/hcloud-go@v1.33.2/hcloud/action.go:196 +0x1b7
created by github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress
        github.com/hetznercloud/hcloud-go@v1.33.2/hcloud/action.go:189 +0x12e

Error: The terraform-provider-hcloud_v1.33.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

It also happened while creating that the server locks up for some reason:

```
hcloud_server_network.main_network[0]: Creation complete after 9s [id=20591725-1662142]
hcloud_server_network.main_network[2]: Still creating... [10s elapsed]
╷
│ Error: attach server to network: cannot perform operation because server is locked (locked)
│ 
│   with hcloud_server_network.main_network[2],
│   on network.tf line 18, in resource "hcloud_server_network" "main_network":
│   18: resource "hcloud_server_network" "main_network" {
│ 
╵

```

### What did you expect to happen?

Destroy the infra

### Please provide a minimal working example
```terraform
resource "hcloud_network" "priv" {
  name     = "priv"
  ip_range = var.ip_range
}

resource "hcloud_server_network" "main_network" {
  count     = var.core_count + var.node_count
  server_id = element(concat(hcloud_server.core.*.id, hcloud_server.node.*.id), count.index)
  subnet_id = hcloud_network_subnet.priv_subnet.id
}

resource "hcloud_network_subnet" "priv_subnet" {
  network_id   = hcloud_network.priv.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = var.cloud_subnet
}
```

**Comment by apricote** [comment]
Hey @pitastrudl,

unfortunatly I am unable to reproduce your issue. I tried with your provided example and added `hcloud_sever` and `variables` to make it work.

I was able to successfully apply and destroy the full plan with 8 servers.

Are you still able to reproduce this issue? If yes, can you provide me with some detailed steps you follow to get the error.

My configs:

```terraform
# I added these
variable node_count { default = "4" }
variable core_count { default = 4 }
variable ip_range { default = "10.0.0.0/16" }
variable cloud_subnet { default = "10.0.0.0/24" }

resource "hcloud_server" "node" {
  count = var.node_count
  server_type = "cx11"
  name = "node-${count.index}"
  image = "ubuntu-20.04"
  location = "hel1"
}

resource "hcloud_server" "core" {
  count = var.node_count
  server_type = "cx11"
  name = "core-${count.index}"
  image = "ubuntu-20.04"
  location = "hel1"
}

# Your provided minimal working example:
resource "hcloud_network" "priv" {
  name     = "priv"
  ip_range = var.ip_range
}

resource "hcloud_server_network" "main_network" {
  count     = var.core_count + var.node_count
  server_id = element(concat(hcloud_server.core.*.id, hcloud_server.node.*.id), count.index)
  subnet_id = hcloud_network_subnet.priv_subnet.id
}

resource "hcloud_network_subnet" "priv_subnet" {
  network_id   = hcloud_network.priv.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = var.cloud_subnet
}
```

Commands:

```shell
terraform apply
terraform destroy
```

**Comment by jenyapoyarkov** [comment]
I've run into this issue while I was using [kube-hetzner](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner). 

During my investigation, I learnt that one of the control-plane hosts cannot be detached from the private network for some reason, so the [DetachFromNetwork](https://github.com/hetznercloud/terraform-provider-hcloud/blob/78e66e2f7ead0ad1bc6e44328cc7ed7199b2ee77/internal/server/resource_network.go#L336) function returned `server_error` that can't be handled properly according to the current logic:

<img width="186" alt="image" src="https://user-images.githubusercontent.com/1634282/201082065-8c848806-d37b-49ce-aefa-361b2a70e74c.png">

Call stack:

```
github.com/hetznercloud/hcloud-go/hcloud.(*ServerClient).DetachFromNetwork (.../hcloud-go/hcloud/server.go:1035)
github.com/hetznercloud/terraform-provider-hcloud/internal/server.detachServerFromNetwork.func1 (.../terraform-provider-hcloud/internal/server/resource_network.go:336)
github.com/hetznercloud/terraform-provider-hcloud/internal/control.Retry (.../terraform-provider-hcloud/internal/control/retry.go:43)
github.com/hetznercloud/terraform-provider-hcloud/internal/server.detachServerFromNetwork (.../terraform-provider-hcloud/internal/server/resource_network.go:333)
```

**Comment by apricote** [comment]
Hi @pitastrudl, I am going to close this issue as it is a duplicate of #491. Please use that ticket for any further comments.

If you still have the issue, it would be great if you can send me debug logs, I describe the process for that here: https://github.com/hetznercloud/terraform-provider-hcloud/issues/491#issuecomment-1324848120

**Comment by apricote** [comment]
@evgenypoyarkov This does not seem to be related to the original issue, please open a new issue for this.
