### ISSUE TITLE
[Bug]: Crash during server creation with invalid image name

### ISSUE THREAD

**Issue by xoxys** [hetznercloud/terraform-provider-hcloud#570]
### What happened?

Creating a `hcloud_server` resource with an `image` that does not exist results in a plugin crash.

```
╷
│ Error: Request cancelled
│ 
│   with module.server.hcloud_server.server["myserver"],
│   on .terraform/modules/server/main.tf line 47, in resource "hcloud_server" "server":
│   47: resource "hcloud_server" "server" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-hcloud_v1.35.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0xb7ca1e]

goroutine 67 [running]:
github.com/hetznercloud/hcloud-go/hcloud.(*Image).IsDeprecated(...)
	github.com/hetznercloud/hcloud-go@v1.35.1/hcloud/image.go:40
github.com/hetznercloud/terraform-provider-hcloud/internal/server.resourceServerCreate({0xe94c80, 0xc0003ccf00}, 0xc55ac0?, {0xcad3e0?, 0xc0004319e0?})
	github.com/hetznercloud/terraform-provider-hcloud/internal/server/resource.go:289 +0x2be
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0005501c0, {0xe94cb8, 0xc0002999e0}, 0xd?, {0xcad3e0, 0xc0004319e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0005501c0, {0xe94cb8, 0xc0002999e0}, 0xc0002256c0, 0xc000313800, {0xcad3e0, 0xc0004319e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000290018, {0xe94c10?, 0xc000304cc0?}, 0xc000402cd0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002c2000, {0xe94cb8?, 0xc000299200?}, 0xc0008201c0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd25ee0?, 0xc0002c2000}, {0xe94cb8, 0xc000299200}, 0xc0003cc720, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000141500, {0xe98110, 0xc00031b1e0}, 0xc0003dd0e0, 0xc00028e420, 0x13a5fc0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000141500, {0xe98110, 0xc00031b1e0}, 0xc0003dd0e0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-hcloud_v1.35.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### What did you expect to happen?

No crash.

### Please provide a minimal working example

```
resource "hcloud_server" "node1" {
  name        = "node1"
  image       = "no-image-with-this-name"
  server_type = "cx11"
}
```

**Comment by 4ND3R50N** [comment]
Using your example, i get:

**` image no-image-with-this-name not found`**

I also see that youre using the version `v1.35.0`. Can you retry it with `v1.35.2`?

If you still encounter this problem, feel free to comment this issue with a new minimal working example :-)

**Comment by xoxys** [comment]
Thanks. Was addressed by https://github.com/hetznercloud/terraform-provider-hcloud/pull/553
