### ISSUE TITLE
[Bug]: segmentation violation in DeleteSubnet

### ISSUE THREAD

**Issue by patope** [hetznercloud/terraform-provider-hcloud#684]
### What happened?

```
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
Stack trace from the terraform-provider-hcloud_v1.39.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb297b1]
goroutine 184 [running]:
github.com/hetznercloud/hcloud-go/hcloud.(*NetworkClient).DeleteSubnet(0xc0001d4678, {0xf181e8, 0xc0001bf260}, 0x0, {{{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, ...}, ...}})
	github.com/hetznercloud/hcloud-go@v1.45.1/hcloud/network.go:368 +0xb1
github.com/hetznercloud/terraform-provider-hcloud/internal/network.resourceNetworkSubnetDelete.func1()
	github.com/hetznercloud/terraform-provider-hcloud/internal/network/resource_subnet.go:165 +0x34b
github.com/hetznercloud/terraform-provider-hcloud/internal/control.Retry(0x32, 0xc0000bae28)
	github.com/hetznercloud/terraform-provider-hcloud/internal/control/retry.go:43 +0xd4
github.com/hetznercloud/terraform-provider-hcloud/internal/network.resourceNetworkSubnetDelete({0xf181e8, 0xc0001bf260}, 0xc000131a80, {0xd146c0?, 0xc0001d45a0})
	github.com/hetznercloud/terraform-provider-hcloud/internal/network/resource_subnet.go:154 +0x10a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc0004696c0, {0xf18220, 0xc0001f2690}, 0xd?, {0xd146c0, 0xc0001d45a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:758 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004696c0, {0xf18220, 0xc0001f2690}, 0xc00068fba0, 0xc000131a00, {0xd146c0, 0xc0001d45a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:806 +0x605
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0004eee58, {0xf18220?, 0xc0001f2480?}, 0xc00060d310)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001537c0, {0xf18220?, 0xc000519bf0?}, 0xc0000f99d0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd90a60?, 0xc0001537c0}, {0xf18220, 0xc000519bf0}, 0xc0000f9880, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004fc000, {0xf1c960, 0xc0001b11e0}, 0xc0006b1680, 0xc000518810, 0x146a300, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0004fc000, {0xf1c960, 0xc0001b11e0}, 0xc0006b1680, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a
Error: The terraform-provider-hcloud_v1.39.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### What did you expect to happen?

not to crash

### Please provide a minimal working example

-

**Comment by apricote** [comment]
Hey @patope, I am unable to reproduce this issue with the example from the subnet docs:

```tf
resource "hcloud_network" "mynet" {
  name     = "my-net"
  ip_range = "10.0.0.0/8"
}
resource "hcloud_network_subnet" "foonet" {
  network_id   = hcloud_network.mynet.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/24"
}
```

```terminal
terraform apply
terraform destroy
```

Can you reproduce this issue? If yes, it would be very helpful if you can provide a minimal working example, or logs for a run that crashed. You can generate logs by running `TF_LOG=TRACE TF_LOG_PATH=crash-destory-subnet.log terraform apply`. You can then send the logs to me (`julian.toelle <at> hetzner-cloud.de`)
