### ISSUE TITLE
[Bug]: [SIGSEGV] Crash while creating infrastructure

### ISSUE THREAD

**Issue by akoskovacs** [hetznercloud/terraform-provider-hcloud#822]
### What happened?

I got this crash while attempting to create the infrastructure:
```
Plan: 8 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

hcloud_ssh_key.mhz_ssh_key: Creating...
hcloud_network.mhz_euc_fsn1_inet: Creating...
hcloud_managed_certificate.mhz_cert_marqraft_grund_com: Creating...
hcloud_load_balancer.mhz_euc_fsn1_lb_001: Creating...
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: name is already used (uniqueness_error)
│ 
│   with hcloud_network.mhz_euc_fsn1_inet,
│   on main.tf line 14, in resource "hcloud_network" "mhz_euc_fsn1_inet":
│   14: resource "hcloud_network" "mhz_euc_fsn1_inet" {
│ 
╵

Stack trace from the terraform-provider-hcloud_v1.44.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa7b445]

goroutine 96 [running]:
github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress.func1()
        github.com/hetznercloud/hcloud-go@v1.51.0/hcloud/action.go:153 +0x1c5
created by github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress in goroutine 42
        github.com/hetznercloud/hcloud-go@v1.51.0/hcloud/action.go:145 +0x11b

Error: The terraform-provider-hcloud_v1.44.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Used resources:

- hcloud_network
- hcloud_ssh_key
- hcloud_server
- hcloud_managed_certificate
- hcloud_load_balancer
- hcloud_load_balancer_target
- hcloud_load_balancer_network
- hcloud_load_balancer_service

Provider:
```
terraform {
  required_version = ">=1.6.6"
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.44.1"
    }
  }
}
```

### What did you expect to happen?

For the plugin to not crash and the infrastructure to be created.

### Please provide a minimal working example

I can provide the full terraform file privately.

**Comment by akoskovacs** [comment]
The problem was caused by the certificate from another project still being used. After deleting it and every resource associated to it, the problem was solved and the infrastructure was created.
Although the runtime crashes didn't help and still might still show a null-pointer dereference somewhere.

**Comment by jooola** [comment]
@akoskovacs Could you provide us with a minimal reproduction example please? I am afraid that hunting down a nil pointer dereference with the trace you provided will be a nightmare.

**Comment by flonix8** [comment]
I just hit the exact same issue, running `terraform-provider-hcloud_v1.45.0` with `hcloud-go@v1.53.0`. The problem is, that I cannot easily delete the certificates from other projects, because those are being actively used.

My stacktrace:
```
Stack trace from the terraform-provider-hcloud_v1.45.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa8fa85]

goroutine 138 [running]:
github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress.func1()
        github.com/hetznercloud/hcloud-go@v1.53.0/hcloud/action.go:153 +0x1c5
created by github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress in goroutine 58
        github.com/hetznercloud/hcloud-go@v1.53.0/hcloud/action.go:145 +0x11b

Error: The terraform-provider-hcloud_v1.45.0 plugin crashed!
```

**Comment by flonix8** [comment]
I have done some experimenting and can confirm what  @akoskovacs said: The issue seems to be that a certificate for the domain in question already exists (in my case it's located in another project). It does make sense to me that it shouldn't work, now that I think about it, but the plugin should (in my opinion) not crash but ideally give a helpful hint towards the error.

**Comment by apricote** [comment]
I was able to reproduce by having a managed certificate with the exact same domains in another project.

Here are the logs, including API requests:

```
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud: --- Request:
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud: POST /v1/certificates HTTP/1.1
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud: Host: api.hetzner.cloud
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud: User-Agent: hcloud-terraform/not build yet hcloud-go/1.52.0
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud: Content-Length: 100
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud: Authorization: REDACTED
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud: Content-Type: application/json
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud: Accept-Encoding: gzip
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud: {"name":"tf-822","type":"managed","domain_names":["hc-integrations.de","tf-822.hc-integrations.de"]}
2024-01-19T14:01:58.288+0100 [DEBUG] provider.terraform-provider-hcloud
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: --- Response:
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: HTTP/2.0 200 OK
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: Content-Length: 134
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: Access-Control-Allow-Credentials: true
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: Access-Control-Allow-Headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: Access-Control-Allow-Origin: *
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: Access-Control-Max-Age: 1728000
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: Content-Type: application/json
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: Date: Fri, 19 Jan 2024 13:01:58 GMT
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: Strict-Transport-Security: max-age=15724800; includeSubDomains
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: X-Correlation-Id: 9d29279c6da1d815
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: X-Request-Id: 6bdd3a03-979c-45c1-8c0b-c1e45b90db63
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: {
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud:     "error": {
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud:         "code": "uniqueness_error",
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud:         "message": "certificate with exact set of domains already exists"
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud:     }
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud: }
2024-01-19T14:01:58.465+0100 [DEBUG] provider.terraform-provider-hcloud
2024-01-19T14:01:58.468+0100 [DEBUG] provider.terraform-provider-hcloud: panic: runtime error: invalid memory address or nil pointer dereference
2024-01-19T14:01:58.468+0100 [DEBUG] provider.terraform-provider-hcloud: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa81325]
2024-01-19T14:01:58.468+0100 [DEBUG] provider.terraform-provider-hcloud
2024-01-19T14:01:58.468+0100 [DEBUG] provider.terraform-provider-hcloud: goroutine 81 [running]:
2024-01-19T14:01:58.468+0100 [DEBUG] provider.terraform-provider-hcloud: github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress.func1()
2024-01-19T14:01:58.468+0100 [DEBUG] provider.terraform-provider-hcloud: 	/home/julian/go/pkg/mod/github.com/hetznercloud/hcloud-go@v1.52.0/hcloud/action.go:153 +0x1c5
2024-01-19T14:01:58.468+0100 [DEBUG] provider.terraform-provider-hcloud: created by github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress in goroutine 12
2024-01-19T14:01:58.468+0100 [DEBUG] provider.terraform-provider-hcloud: 	/home/julian/go/pkg/mod/github.com/hetznercloud/hcloud-go@v1.52.0/hcloud/action.go:145 +0x11b
```

Reproduction TF:

```terraform
resource "hcloud_managed_certificate" "managed_cert" {
  name         = "tf-822"
  domain_names = ["tf-822.hc-integrations.de", "hc-integrations.de"]
}
```

**Comment by apricote** [comment]
Figured out what is happening, in talks with the team responsible for this endpoint. It affects anything using `hcloud-go` at least.

- We try to create the certificate
- API responds with `200 OK` but the body only contains the `uniqueness_error`
- `hcloud-go` only parses errors when status code `>= 400 && <= 599` ([source](https://github.com/hetznercloud/hcloud-go/blob/2f334c3de2aecfb7aaf179424bb9a1a7b0da53ea/hcloud/client.go#L289-L299))
- As no error is returned from the API call, Terraform assumes everything is fine and continues ([source](https://github.com/hetznercloud/terraform-provider-hcloud/blob/a5229f492c5cee0bede74354ad697c452bd55211/internal/certificate/resource.go#L229-L236))
- Terraform tries to wait for the action it expects in the body, but there is none -> nil pointer dereference somewhere deeper in the stack

**Comment by apricote** [comment]
@flonix8 @akoskovacs A fix to the API was just deployed and you should see the proper error message again:

```
hcloud_managed_certificate.managed_cert: Creating...
╷
│ Error: certificate with exact set of domains already exists (uniqueness_error)
│ 
│   with hcloud_managed_certificate.managed_cert,
│   on 822.tf line 1, in resource "hcloud_managed_certificate" "managed_cert":
│    1: resource "hcloud_managed_certificate" "managed_cert" {
│ 
╵
```

Sorry for the inconvenience and thanks for the detailed reproduction steps.

**Comment by flonix8** [comment]
This is what I call a prompt reaction (and fix). Thank you!
